  server:
    port: 8130
  spring:
    cloud:
      nacos:
        discovery:
          server-addr: localhost:8848
    profiles:
      active: dev
    application:
      name: service-oss
  aliyun:
    oss:
      endPoint: oss-cn-beijing.aliyuncs.com
      keyId: // your keyId
      keySecret: // your keySercret
      bucketName: srb-file-wenshuo
